In [2]:
# libraries
import numpy as np
import pandas as pd

In [3]:
#options
pd.set_option('display.max_columns', None)

In [4]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [5]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [6]:
# encode - map
mtcars['am'] = mtcars['am'].map({0: 'auto', 1: 'manual'})
mtcars.head()
#mtcars['am'] = mtcars['am'].replace({0: 'auto', 1: 'manual'})

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [7]:
mtcars['vs'] = mtcars['vs'].map({0:'vshaped', 1:'straight' })
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,straight,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,auto,3,2

In [9]:
mtcars[mtcars['cyl'] > 5].sort_values('cyl', ascending=True)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,auto,3,1
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,straight,auto,3,1
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,straight,auto,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,straight,auto,4,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,vshaped,manual,5,6
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,vshaped,manual,5,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,vshaped,auto,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,vshaped,auto,3,4
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,vshaped,auto,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,vshaped,auto,3,2
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,vshaped,auto,3,4
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,vshaped,auto,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,vshaped,auto,3,4
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,vshaped,auto,3,3
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,vshaped,auto,3,3
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,vshaped,auto,3,4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,auto,3,2
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,vshaped,auto,3,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,vshaped,manual,5,8

In [10]:
mtcars[mtcars['cyl'] > 5] 9if you have converted the type to category the greater than function will not work, as it chnaged from numerical to

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,auto,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,straight,auto,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,vshaped,auto,3,4
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,straight,auto,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,straight,auto,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,vshaped,auto,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,vshaped,auto,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,vshaped,auto,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,vshaped,auto,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,vshaped,auto,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,vshaped,auto,3,4
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,vshaped,auto,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,vshaped,auto,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,vshaped,auto,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,vshaped,auto,3,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,vshaped,manual,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,vshaped,manual,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,vshaped,manual,5,8

In [14]:
pd.pivot_table( observed=True , data= mtcars,  index='gear',  columns='am',  values='mpg', 
                aggfunc=['mean', 'max', 'min' ,'count','sum'] ).reset_index()

   gear       mean           max          min        count           sum  \
am            auto  manual  auto manual  auto manual  auto manual   auto
0     3  16.106667     NaN  21.5    NaN  10.4    NaN  15.0    NaN  241.6
1     4  21.050000  26.275  24.4   33.9  17.8   21.0   4.0    8.0   84.2
2     5        NaN  21.380   NaN   30.4   NaN   15.0   NaN    5.0    NaN


am manual
0     NaN
1   210.2
2   106.9

In [15]:
pd.pivot_table(data= mtcars,  index=['gear','am'],  columns='cyl',  values='mpg', \
                aggfunc=['mean', 'max', 'min' ,'count','sum','std'] ).reset_index()

    gear      am       mean                 max               min              \
cyl                       4      6      8     4     6     8     4     6     8
0      3    auto  21.500000  19.75  15.05  21.5  21.4  19.2  21.5  18.1  10.4
1      4    auto  23.600000  18.50    NaN  24.4  19.2   NaN  22.8  17.8   NaN
2      4  manual  28.033333  21.00    NaN  33.9  21.0   NaN  21.4  21.0   NaN
3      5  manual  28.200000  19.70  15.40  30.4  19.7  15.8  26.0  19.7  15.0

    count               sum                    std
cyl     4    6     8      4     6      8         4         6         8
0     1.0  2.0  12.0   21.5  39.5  180.6       NaN  2.333452  2.774396
1     2.0  2.0   NaN   47.2  37.0    NaN  1.131371  0.989949       NaN
2     6.0  2.0   NaN  168.2  42.0    NaN  5.118854  0.000000       NaN
3     2.0  1.0   2.0   56.4  19.7   30.8  3.111270       NaN  0.565685