In [2]:
# libraries
import numpy as np
import pandas as pd

In [4]:
#options
pd.set_option('display.max_columns', None)

In [37]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [21]:
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [11]:
mtcars = data('mtcars')
mtcars = mtcars.astype({'cyl':'category', 'vs':'category', 'carb':'category', 'am':'category', 'gear': 'category'})

In [12]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [14]:
mtcars.head(3)

                mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4      21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag  21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710     22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1

In [15]:
# encode - map
mtcars['am'] = mtcars['am'].map({0: 'auto', 1: 'manual'})
mtcars.head()
#mtcars['am'] = mtcars['am'].replace({0: 'auto', 1: 'manual'})

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [16]:
mtcars['gear'].value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [22]:
mtcars['gear'] = mtcars['gear'].map({3: 'Gear3', 4: 'gear4', 5: 'gear5'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,gear4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,gear4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,gear4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,Gear3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,Gear3,2

In [23]:
mtcars['gear'].value_counts()

gear
Gear3    15
gear4    12
gear5     5
Name: count, dtype: int64

In [24]:
mtcars['mpg'].max()

33.9

In [25]:
mtcars[mtcars['mpg'] == 33.9]

                 mpg  cyl  disp  hp  drat     wt  qsec  vs  am   gear  carb
Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1  gear4     1

In [26]:
mtcars[mtcars['mpg'] > 30].sort_values('mpg')

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am   gear  carb
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1  gear4     2
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1  gear5     2
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1  gear4     1
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1  gear4     1

In [27]:
mtcars[mtcars['mpg'] > 30].sort_values('mpg', ascending = False)

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am   gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1  gear4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1  gear4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1  gear4     2
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1  gear5     2

In [29]:
mtcars[mtcars['mpg'] == mtcars['mpg'].min()]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,Gear3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,Gear3,4

In [30]:
mtcars[mtcars['mpg'] == mtcars['mpg'].max()]

                 mpg  cyl  disp  hp  drat     wt  qsec  vs  am   gear  carb
Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1  gear4     1

In [31]:
mtcars[mtcars['mpg'] >= mtcars['mpg'].mean()]

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am   gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1  gear4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1  gear4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1  gear4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0  Gear3     1
Merc 240D       24.4    4  146.7   62  3.69  3.190  20.00   1   0  gear4     2
Merc 230        22.8    4  140.8   95  3.92  3.150  22.90   1   0  gear4     2
Fiat 128        32.4    4   78.7   66  4.08  2.200  19.47   1   1  gear4     1
Honda Civic     30.4    4   75.7   52  4.93  1.615  18.52   1   1  gear4     2
Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1  gear4     1
Toyota Corona   21.5    4  120.1   97  3.70  2.465  20.01   1   0  Gear3     1
Fiat X1-9       27.3    4   79.0   66  4.08  1.935  18.90   1   1  gear4     1
Porsche 914-2   26.0    4  120.3   91  4.43  2.140  16.70   0   1  gear5     2
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.90   1   1  gear5     2
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.60   1   1  gear4     2

In [33]:
bins = [0, 17, 29, mtcars['mpg'].max()]
labels = ['Low', 'Medium', 'High']

# Create the new categorical column
mtcars['mpg_level'] = pd.cut(mtcars['mpg'], bins=bins, labels=labels, include_lowest=True)

In [42]:
bins = [0, 17, 29, mtcars['mpg'].max()]
labels = ['Low', 'Medium', 'High']

# Create the new categorical column
mtcars['mpg_level'] = pd.cut(mtcars['mpg'], bins=bins, labels=labels, include_lowest=True)

In [43]:
mtcars['hp_level'].value_counts()

hp_level
Medium       14
High         11
Low           5
Very High     2
Name: count, dtype: int64

In [38]:
bins = [0, 70, 150, 250, mtcars['hp'].max()]
labels = ['Low', 'Medium', 'High', 'Very High']

mtcars['hp_level'] = pd.cut(mtcars['hp'], bins=bins, labels=labels, include_lowest=True)

In [39]:
mtcars['hp_level'].value_counts()

hp_level
Medium       14
High         11
Low           5
Very High     2
Name: count, dtype: int64

In [44]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,mpg_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Medium,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Medium,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Medium,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Medium,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,High,Medium

In [45]:
print(len(mtcars[mtcars['mpg'] > 25]))
mtcars[mtcars['mpg'] > 25]
# list cars with mileage more than 25

6

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,mpg_level
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Low,High
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Low,High
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Low,High
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Low,Medium
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,Medium,Medium
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Medium,High