In [3]:
# libraries
import numpy as np
import pandas as pd

In [4]:
#options
pd.set_option('display.max_columns', None)

In [5]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [10]:
data = [
    [1, 'Taheera', 70, 86], [2, 'Aelita', 56, 90], [3, 'Khulan', 87, 90], [4, 'Batgerel', 71, 79],[5, 'Manisha', 88, 76]]
df = pd.DataFrame(data, columns=['Rollno', 'Name', 'Maths', 'English'])

In [11]:
df

   Rollno      Name  Maths  English
0       1   Taheera     70       86
1       2    Aelita     56       90
2       3    Khulan     87       90
3       4  Batgerel     71       79
4       5   Manisha     88       76

In [14]:
df_long = df.melt(id_vars=['Rollno','Name'],value_vars=['Maths','English'],var_name='Subject',value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3    Khulan    Maths     87
3       4  Batgerel    Maths     71
4       5   Manisha    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3    Khulan  English     90
8       4  Batgerel  English     79
9       5   Manisha  English     76

In [19]:
wide_df = df_long.pivot(index=['Rollno','Name'],values='Marks').reset_index()
wide_df

TypeError: DataFrame.pivot() missing 1 required keyword-only argument: 'columns'

In [20]:
wide_df = df_long.pivot(index=['Rollno','Name'],columns='Subject',values='Marks').reset_index()
wide_df

Subject  Rollno      Name  English  Maths
0             1   Taheera       86     70
1             2    Aelita       90     56
2             3    Khulan       90     87
3             4  Batgerel       79     71
4             5   Manisha       76     88

In [17]:
wide_df = df_long.pivot(index=['Rollno','Name'], columns='Subject',
             values='Marks').reset_index(drop=False).rename_axis(None, axis=1)
wide_df

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88

In [18]:
wide_df2 = df_long.pivot_table(index=['Rollno','Name'], columns='Subject',
                               values='Marks', aggfunc='sum').reset_index(drop=False).rename_axis(None, axis=1)
wide_df2

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88