# SQL Python Connect

In [1]:
# libraries (install if required)
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [2]:
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [3]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [4]:
q('show tables')

  Tables_in_piit
0         aelita
1           dept
2            emp
3       students

In [6]:
q('select * from dept')

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [8]:
q('select * from emp')

    empno    ename        job     mgr    hiredate     sal    comm  deptno
0    1236  MANISHA    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    7369    SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
2    7499    ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
3    7521     WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4    7566    JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
5    7654   MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
6    7698    BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
7    7782    CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
8    7788    SCOTT    ANALYST  7566.0  1982-12-09  3000.0     NaN      20
9    7839     KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
10   7844   TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
11   7876    ADAMS      CLERK  7788.0  1983-01-12  1100.0     NaN      20
12   7900    JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
13   7902     FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
14   7934   MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [9]:
emp = q('select * from emp')
emp.head()

   empno    ename       job     mgr    hiredate     sal   comm  deptno
0   1236  MANISHA   ANALYST  7839.0  1988-12-17  5000.0  100.0      10
1   7369    SMITH     CLERK  7902.0  1980-12-17   800.0    NaN      20
2   7499    ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0      30
3   7521     WARD  SALESMAN  7698.0  1981-02-22  1250.0  500.0      30
4   7566    JONES   MANAGER  7839.0  1981-04-02  2975.0    NaN      20

In [10]:
dept = q('select * from dept')
dept.head()

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [13]:
empdept= pd.merge(emp, dept, on='deptno', how='inner')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1236,MANISHA,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
2,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
3,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
4,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS

In [16]:
empdept.groupby('dname').size() #gives how many people are in how many department

dname
ACCOUNTING    4
RESEARCH      5
SALES         6
dtype: int64

In [17]:
emp = q('select * from emp')
dept = q('select * from dept')

In [18]:
empdept = emp.merge(dept, on='deptno', how='inner')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1236,MANISHA,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
2,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
3,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
4,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS

In [25]:
empnull = q('select count(*) from emp where comm is Null')
# Employees earning above dept average; here we have subqueryempnull

   count(*)
0        10

In [28]:
# Employees earning above dept average; here we have subquery

q('select ename, sal, deptno from emp e where sal > (select avg(sal) from emp where deptno = deptno)')

     ename     sal  deptno
0  MANISHA  5000.0      10
1    JONES  2975.0      20
2    BLAKE  2850.0      30
3    CLARK  2450.0      10
4    SCOTT  3000.0      20
5     KING  5000.0      10
6     FORD  3000.0      20

In [34]:
# Departments with the highest average salary
q('select d.dname, avg(e.sal) as avg_salary from emp e join dept d on e.deptno = d.deptno group by d.dname')

        dname   avg_salary
0  ACCOUNTING  3437.500000
1    RESEARCH  2175.000000
2       SALES  1566.666667

In [33]:
# Department with the highest average salary 
q('select d.dname, avg(e.sal) as avg_salary from emp e join dept d on e.deptno = d.deptno group by d.dname limit 1')

        dname  avg_salary
0  ACCOUNTING      3437.5

In [35]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     15 non-null     int64
 1   ename     15 non-null     object
 2   job       15 non-null     object
 3   mgr       14 non-null     float64
 4   hiredate  15 non-null     object
 5   sal       15 non-null     float64
 6   comm      5 non-null      float64
 7   deptno    15 non-null     int64
 8   dname     15 non-null     object
 9   loc       15 non-null     object
dtypes: float64(3), int64(2), object(5)
memory usage: 1.3+ KB

In [37]:
empdept['hiredate'] = pd.to_datetime(empdept['hiredate'])

In [38]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     15 non-null     int64
 1   ename     15 non-null     object
 2   job       15 non-null     object
 3   mgr       14 non-null     float64
 4   hiredate  15 non-null     datetime64[ns]
 5   sal       15 non-null     float64
 6   comm      5 non-null      float64
 7   deptno    15 non-null     int64
 8   dname     15 non-null     object
 9   loc       15 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 1.3+ KB

In [39]:
empdept['hireyear'] = empdept['hiredate'].dt.year
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,1236,MANISHA,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,1988
1,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS,1980
2,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981
3,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981
4,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS,1981

In [40]:
empdept[empdept['hireyear'] >= 1982]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,1236,MANISHA,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,1988
8,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
11,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983
14,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK,1982

In [43]:
empdept[(empdept['hireyear'] >= 1982) & (empdept['dname'] =='RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
8,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
11,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983

In [44]:
empdept[(empdept['hiredate'].dt.year >= 1982) & (empdept['dname'] =='RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
8,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
11,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983